import sys
sys.stdout.reconfigure(encoding="utf-8")
print("starting...")
from playwright.sync_api import sync_playwright
print("imported")
p = sync_playwright().start()
print("started")
b = p.chromium.launch(headless=True)
print("browser launched")
page = b.new_page()
page.goto("https://example.com", timeout=15000)
print("title:", page.title())
b.close()
p.stop()
print("done")
